// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binarydataarray.proto

package PB.com.toptrade.ra.stockdata;

public final class BinaryData {
  private BinaryData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BinaryDataArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PB.com.toptrade.ra.stockdata.BinaryDataArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDataArrayList();
    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    int getDataArrayCount();
    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    com.google.protobuf.ByteString getDataArray(int index);
  }
  /**
   * Protobuf type {@code PB.com.toptrade.ra.stockdata.BinaryDataArray}
   */
  public static final class BinaryDataArray extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PB.com.toptrade.ra.stockdata.BinaryDataArray)
      BinaryDataArrayOrBuilder {
    // Use BinaryDataArray.newBuilder() to construct.
    private BinaryDataArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BinaryDataArray(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BinaryDataArray defaultInstance;
    public static BinaryDataArray getDefaultInstance() {
      return defaultInstance;
    }

    public BinaryDataArray getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BinaryDataArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataArray_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataArray_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataArray_ = java.util.Collections.unmodifiableList(dataArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PB.com.toptrade.ra.stockdata.BinaryData.internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PB.com.toptrade.ra.stockdata.BinaryData.internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.class, PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.Builder.class);
    }

    public static com.google.protobuf.Parser<BinaryDataArray> PARSER =
        new com.google.protobuf.AbstractParser<BinaryDataArray>() {
      public BinaryDataArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BinaryDataArray(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BinaryDataArray> getParserForType() {
      return PARSER;
    }

    public static final int DATAARRAY_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> dataArray_;
    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDataArrayList() {
      return dataArray_;
    }
    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    public int getDataArrayCount() {
      return dataArray_.size();
    }
    /**
     * <code>repeated bytes dataArray = 1;</code>
     */
    public com.google.protobuf.ByteString getDataArray(int index) {
      return dataArray_.get(index);
    }

    private void initFields() {
      dataArray_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dataArray_.size(); i++) {
        output.writeBytes(1, dataArray_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < dataArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dataArray_.get(i));
        }
        size += dataSize;
        size += 1 * getDataArrayList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PB.com.toptrade.ra.stockdata.BinaryDataArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PB.com.toptrade.ra.stockdata.BinaryDataArray)
        PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PB.com.toptrade.ra.stockdata.BinaryData.internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PB.com.toptrade.ra.stockdata.BinaryData.internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.class, PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.Builder.class);
      }

      // Construct using PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dataArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PB.com.toptrade.ra.stockdata.BinaryData.internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor;
      }

      public PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray getDefaultInstanceForType() {
        return PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.getDefaultInstance();
      }

      public PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray build() {
        PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray buildPartial() {
        PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray result = new PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dataArray_ = java.util.Collections.unmodifiableList(dataArray_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dataArray_ = dataArray_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray) {
          return mergeFrom((PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray other) {
        if (other == PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray.getDefaultInstance()) return this;
        if (!other.dataArray_.isEmpty()) {
          if (dataArray_.isEmpty()) {
            dataArray_ = other.dataArray_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataArrayIsMutable();
            dataArray_.addAll(other.dataArray_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PB.com.toptrade.ra.stockdata.BinaryData.BinaryDataArray) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> dataArray_ = java.util.Collections.emptyList();
      private void ensureDataArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataArray_ = new java.util.ArrayList<com.google.protobuf.ByteString>(dataArray_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataArrayList() {
        return java.util.Collections.unmodifiableList(dataArray_);
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public int getDataArrayCount() {
        return dataArray_.size();
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public com.google.protobuf.ByteString getDataArray(int index) {
        return dataArray_.get(index);
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public Builder setDataArray(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataArrayIsMutable();
        dataArray_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public Builder addDataArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataArrayIsMutable();
        dataArray_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public Builder addAllDataArray(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataArrayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataArray_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes dataArray = 1;</code>
       */
      public Builder clearDataArray() {
        dataArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PB.com.toptrade.ra.stockdata.BinaryDataArray)
    }

    static {
      defaultInstance = new BinaryDataArray(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PB.com.toptrade.ra.stockdata.BinaryDataArray)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025binarydataarray.proto\022\034PB.com.toptrade" +
      ".ra.stockdata\"$\n\017BinaryDataArray\022\021\n\tdata" +
      "Array\030\001 \003(\014B\014B\nBinaryData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PB_com_toptrade_ra_stockdata_BinaryDataArray_descriptor,
        new java.lang.String[] { "DataArray", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
