// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstantNews.proto

package PB.instantnews;

public final class InstantNewsTypes {
  private InstantNewsTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code PB.instantnews.InstantNewsType}
   */
  public enum InstantNewsType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NORMAL = 1;</code>
     */
    NORMAL(0, 1),
    /**
     * <code>EXCEPTIONAL = 2;</code>
     */
    EXCEPTIONAL(1, 2),
    ;

    /**
     * <code>NORMAL = 1;</code>
     */
    public static final int NORMAL_VALUE = 1;
    /**
     * <code>EXCEPTIONAL = 2;</code>
     */
    public static final int EXCEPTIONAL_VALUE = 2;


    public final int getNumber() { return value; }

    public static InstantNewsType valueOf(int value) {
      switch (value) {
        case 1: return NORMAL;
        case 2: return EXCEPTIONAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstantNewsType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<InstantNewsType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InstantNewsType>() {
            public InstantNewsType findValueByNumber(int number) {
              return InstantNewsType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PB.instantnews.InstantNewsTypes.getDescriptor().getEnumTypes().get(0);
    }

    private static final InstantNewsType[] VALUES = values();

    public static InstantNewsType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private InstantNewsType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PB.instantnews.InstantNewsType)
  }

  public interface InstantNewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PB.instantnews.InstantNews)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 1;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 1;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required string time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>required string title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required string contents = 4;</code>
     */
    boolean hasContents();
    /**
     * <code>required string contents = 4;</code>
     */
    java.lang.String getContents();
    /**
     * <code>required string contents = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentsBytes();

    /**
     * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
     */
    boolean hasType();
    /**
     * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
     */
    PB.instantnews.InstantNewsTypes.InstantNewsType getType();

    /**
     * <code>required int32 id = 6;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 6;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code PB.instantnews.InstantNews}
   */
  public static final class InstantNews extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PB.instantnews.InstantNews)
      InstantNewsOrBuilder {
    // Use InstantNews.newBuilder() to construct.
    private InstantNews(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InstantNews(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InstantNews defaultInstance;
    public static InstantNews getDefaultInstance() {
      return defaultInstance;
    }

    public InstantNews getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InstantNews(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              date_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              time_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              title_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              contents_ = bs;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              PB.instantnews.InstantNewsTypes.InstantNewsType value = PB.instantnews.InstantNewsTypes.InstantNewsType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNews_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNews_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PB.instantnews.InstantNewsTypes.InstantNews.class, PB.instantnews.InstantNewsTypes.InstantNews.Builder.class);
    }

    public static com.google.protobuf.Parser<InstantNews> PARSER =
        new com.google.protobuf.AbstractParser<InstantNews>() {
      public InstantNews parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstantNews(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InstantNews> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    /**
     * <code>required string date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>required string title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTS_FIELD_NUMBER = 4;
    private java.lang.Object contents_;
    /**
     * <code>required string contents = 4;</code>
     */
    public boolean hasContents() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string contents = 4;</code>
     */
    public java.lang.String getContents() {
      java.lang.Object ref = contents_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contents_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string contents = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentsBytes() {
      java.lang.Object ref = contents_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contents_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private PB.instantnews.InstantNewsTypes.InstantNewsType type_;
    /**
     * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
     */
    public PB.instantnews.InstantNewsTypes.InstantNewsType getType() {
      return type_;
    }

    public static final int ID_FIELD_NUMBER = 6;
    private int id_;
    /**
     * <code>required int32 id = 6;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 id = 6;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      date_ = "";
      time_ = "";
      title_ = "";
      contents_ = "";
      type_ = PB.instantnews.InstantNewsTypes.InstantNewsType.NORMAL;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContents()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getContentsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getContentsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNews parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PB.instantnews.InstantNewsTypes.InstantNews prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PB.instantnews.InstantNews}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PB.instantnews.InstantNews)
        PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNews_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNews_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PB.instantnews.InstantNewsTypes.InstantNews.class, PB.instantnews.InstantNewsTypes.InstantNews.Builder.class);
      }

      // Construct using PB.instantnews.InstantNewsTypes.InstantNews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contents_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = PB.instantnews.InstantNewsTypes.InstantNewsType.NORMAL;
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNews_descriptor;
      }

      public PB.instantnews.InstantNewsTypes.InstantNews getDefaultInstanceForType() {
        return PB.instantnews.InstantNewsTypes.InstantNews.getDefaultInstance();
      }

      public PB.instantnews.InstantNewsTypes.InstantNews build() {
        PB.instantnews.InstantNewsTypes.InstantNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PB.instantnews.InstantNewsTypes.InstantNews buildPartial() {
        PB.instantnews.InstantNewsTypes.InstantNews result = new PB.instantnews.InstantNewsTypes.InstantNews(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.contents_ = contents_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PB.instantnews.InstantNewsTypes.InstantNews) {
          return mergeFrom((PB.instantnews.InstantNewsTypes.InstantNews)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PB.instantnews.InstantNewsTypes.InstantNews other) {
        if (other == PB.instantnews.InstantNewsTypes.InstantNews.getDefaultInstance()) return this;
        if (other.hasDate()) {
          bitField0_ |= 0x00000001;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContents()) {
          bitField0_ |= 0x00000008;
          contents_ = other.contents_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContents()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PB.instantnews.InstantNewsTypes.InstantNews parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PB.instantnews.InstantNewsTypes.InstantNews) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string date = 1;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contents_ = "";
      /**
       * <code>required string contents = 4;</code>
       */
      public boolean hasContents() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string contents = 4;</code>
       */
      public java.lang.String getContents() {
        java.lang.Object ref = contents_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contents_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string contents = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentsBytes() {
        java.lang.Object ref = contents_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contents_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string contents = 4;</code>
       */
      public Builder setContents(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string contents = 4;</code>
       */
      public Builder clearContents() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }
      /**
       * <code>required string contents = 4;</code>
       */
      public Builder setContentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contents_ = value;
        onChanged();
        return this;
      }

      private PB.instantnews.InstantNewsTypes.InstantNewsType type_ = PB.instantnews.InstantNewsTypes.InstantNewsType.NORMAL;
      /**
       * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNewsType getType() {
        return type_;
      }
      /**
       * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
       */
      public Builder setType(PB.instantnews.InstantNewsTypes.InstantNewsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .PB.instantnews.InstantNewsType type = 5;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = PB.instantnews.InstantNewsTypes.InstantNewsType.NORMAL;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 6;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 id = 6;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 6;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000020;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 6;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PB.instantnews.InstantNews)
    }

    static {
      defaultInstance = new InstantNews(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PB.instantnews.InstantNews)
  }

  public interface InstantNewsPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PB.instantnews.InstantNewsPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    java.util.List<PB.instantnews.InstantNewsTypes.InstantNews> 
        getNewsListList();
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    PB.instantnews.InstantNewsTypes.InstantNews getNewsList(int index);
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    int getNewsListCount();
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    java.util.List<? extends PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder> 
        getNewsListOrBuilderList();
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder getNewsListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PB.instantnews.InstantNewsPack}
   */
  public static final class InstantNewsPack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PB.instantnews.InstantNewsPack)
      InstantNewsPackOrBuilder {
    // Use InstantNewsPack.newBuilder() to construct.
    private InstantNewsPack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InstantNewsPack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InstantNewsPack defaultInstance;
    public static InstantNewsPack getDefaultInstance() {
      return defaultInstance;
    }

    public InstantNewsPack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InstantNewsPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                newsList_ = new java.util.ArrayList<PB.instantnews.InstantNewsTypes.InstantNews>();
                mutable_bitField0_ |= 0x00000001;
              }
              newsList_.add(input.readMessage(PB.instantnews.InstantNewsTypes.InstantNews.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          newsList_ = java.util.Collections.unmodifiableList(newsList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNewsPack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNewsPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PB.instantnews.InstantNewsTypes.InstantNewsPack.class, PB.instantnews.InstantNewsTypes.InstantNewsPack.Builder.class);
    }

    public static com.google.protobuf.Parser<InstantNewsPack> PARSER =
        new com.google.protobuf.AbstractParser<InstantNewsPack>() {
      public InstantNewsPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstantNewsPack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InstantNewsPack> getParserForType() {
      return PARSER;
    }

    public static final int NEWSLIST_FIELD_NUMBER = 1;
    private java.util.List<PB.instantnews.InstantNewsTypes.InstantNews> newsList_;
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    public java.util.List<PB.instantnews.InstantNewsTypes.InstantNews> getNewsListList() {
      return newsList_;
    }
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    public java.util.List<? extends PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder> 
        getNewsListOrBuilderList() {
      return newsList_;
    }
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    public int getNewsListCount() {
      return newsList_.size();
    }
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    public PB.instantnews.InstantNewsTypes.InstantNews getNewsList(int index) {
      return newsList_.get(index);
    }
    /**
     * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
     */
    public PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder getNewsListOrBuilder(
        int index) {
      return newsList_.get(index);
    }

    private void initFields() {
      newsList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getNewsListCount(); i++) {
        if (!getNewsList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < newsList_.size(); i++) {
        output.writeMessage(1, newsList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < newsList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, newsList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.instantnews.InstantNewsTypes.InstantNewsPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PB.instantnews.InstantNewsTypes.InstantNewsPack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PB.instantnews.InstantNewsPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PB.instantnews.InstantNewsPack)
        PB.instantnews.InstantNewsTypes.InstantNewsPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNewsPack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNewsPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PB.instantnews.InstantNewsTypes.InstantNewsPack.class, PB.instantnews.InstantNewsTypes.InstantNewsPack.Builder.class);
      }

      // Construct using PB.instantnews.InstantNewsTypes.InstantNewsPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewsListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (newsListBuilder_ == null) {
          newsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PB.instantnews.InstantNewsTypes.internal_static_PB_instantnews_InstantNewsPack_descriptor;
      }

      public PB.instantnews.InstantNewsTypes.InstantNewsPack getDefaultInstanceForType() {
        return PB.instantnews.InstantNewsTypes.InstantNewsPack.getDefaultInstance();
      }

      public PB.instantnews.InstantNewsTypes.InstantNewsPack build() {
        PB.instantnews.InstantNewsTypes.InstantNewsPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PB.instantnews.InstantNewsTypes.InstantNewsPack buildPartial() {
        PB.instantnews.InstantNewsTypes.InstantNewsPack result = new PB.instantnews.InstantNewsTypes.InstantNewsPack(this);
        int from_bitField0_ = bitField0_;
        if (newsListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            newsList_ = java.util.Collections.unmodifiableList(newsList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.newsList_ = newsList_;
        } else {
          result.newsList_ = newsListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PB.instantnews.InstantNewsTypes.InstantNewsPack) {
          return mergeFrom((PB.instantnews.InstantNewsTypes.InstantNewsPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PB.instantnews.InstantNewsTypes.InstantNewsPack other) {
        if (other == PB.instantnews.InstantNewsTypes.InstantNewsPack.getDefaultInstance()) return this;
        if (newsListBuilder_ == null) {
          if (!other.newsList_.isEmpty()) {
            if (newsList_.isEmpty()) {
              newsList_ = other.newsList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsListIsMutable();
              newsList_.addAll(other.newsList_);
            }
            onChanged();
          }
        } else {
          if (!other.newsList_.isEmpty()) {
            if (newsListBuilder_.isEmpty()) {
              newsListBuilder_.dispose();
              newsListBuilder_ = null;
              newsList_ = other.newsList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewsListFieldBuilder() : null;
            } else {
              newsListBuilder_.addAllMessages(other.newsList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNewsListCount(); i++) {
          if (!getNewsList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PB.instantnews.InstantNewsTypes.InstantNewsPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PB.instantnews.InstantNewsTypes.InstantNewsPack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PB.instantnews.InstantNewsTypes.InstantNews> newsList_ =
        java.util.Collections.emptyList();
      private void ensureNewsListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          newsList_ = new java.util.ArrayList<PB.instantnews.InstantNewsTypes.InstantNews>(newsList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PB.instantnews.InstantNewsTypes.InstantNews, PB.instantnews.InstantNewsTypes.InstantNews.Builder, PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder> newsListBuilder_;

      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public java.util.List<PB.instantnews.InstantNewsTypes.InstantNews> getNewsListList() {
        if (newsListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(newsList_);
        } else {
          return newsListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public int getNewsListCount() {
        if (newsListBuilder_ == null) {
          return newsList_.size();
        } else {
          return newsListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNews getNewsList(int index) {
        if (newsListBuilder_ == null) {
          return newsList_.get(index);
        } else {
          return newsListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder setNewsList(
          int index, PB.instantnews.InstantNewsTypes.InstantNews value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.set(index, value);
          onChanged();
        } else {
          newsListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder setNewsList(
          int index, PB.instantnews.InstantNewsTypes.InstantNews.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder addNewsList(PB.instantnews.InstantNewsTypes.InstantNews value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.add(value);
          onChanged();
        } else {
          newsListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder addNewsList(
          int index, PB.instantnews.InstantNewsTypes.InstantNews value) {
        if (newsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsListIsMutable();
          newsList_.add(index, value);
          onChanged();
        } else {
          newsListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder addNewsList(
          PB.instantnews.InstantNewsTypes.InstantNews.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.add(builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder addNewsList(
          int index, PB.instantnews.InstantNewsTypes.InstantNews.Builder builderForValue) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder addAllNewsList(
          java.lang.Iterable<? extends PB.instantnews.InstantNewsTypes.InstantNews> values) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, newsList_);
          onChanged();
        } else {
          newsListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder clearNewsList() {
        if (newsListBuilder_ == null) {
          newsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public Builder removeNewsList(int index) {
        if (newsListBuilder_ == null) {
          ensureNewsListIsMutable();
          newsList_.remove(index);
          onChanged();
        } else {
          newsListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNews.Builder getNewsListBuilder(
          int index) {
        return getNewsListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder getNewsListOrBuilder(
          int index) {
        if (newsListBuilder_ == null) {
          return newsList_.get(index);  } else {
          return newsListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public java.util.List<? extends PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder> 
           getNewsListOrBuilderList() {
        if (newsListBuilder_ != null) {
          return newsListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(newsList_);
        }
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNews.Builder addNewsListBuilder() {
        return getNewsListFieldBuilder().addBuilder(
            PB.instantnews.InstantNewsTypes.InstantNews.getDefaultInstance());
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public PB.instantnews.InstantNewsTypes.InstantNews.Builder addNewsListBuilder(
          int index) {
        return getNewsListFieldBuilder().addBuilder(
            index, PB.instantnews.InstantNewsTypes.InstantNews.getDefaultInstance());
      }
      /**
       * <code>repeated .PB.instantnews.InstantNews newsList = 1;</code>
       */
      public java.util.List<PB.instantnews.InstantNewsTypes.InstantNews.Builder> 
           getNewsListBuilderList() {
        return getNewsListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PB.instantnews.InstantNewsTypes.InstantNews, PB.instantnews.InstantNewsTypes.InstantNews.Builder, PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder> 
          getNewsListFieldBuilder() {
        if (newsListBuilder_ == null) {
          newsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PB.instantnews.InstantNewsTypes.InstantNews, PB.instantnews.InstantNewsTypes.InstantNews.Builder, PB.instantnews.InstantNewsTypes.InstantNewsOrBuilder>(
                  newsList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          newsList_ = null;
        }
        return newsListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PB.instantnews.InstantNewsPack)
    }

    static {
      defaultInstance = new InstantNewsPack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PB.instantnews.InstantNewsPack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_instantnews_InstantNews_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PB_instantnews_InstantNews_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_instantnews_InstantNewsPack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PB_instantnews_InstantNewsPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021InstantNews.proto\022\016PB.instantnews\"\205\001\n\013" +
      "InstantNews\022\014\n\004date\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022" +
      "\r\n\005title\030\003 \002(\t\022\020\n\010contents\030\004 \002(\t\022-\n\004type" +
      "\030\005 \002(\0162\037.PB.instantnews.InstantNewsType\022" +
      "\n\n\002id\030\006 \002(\005\"@\n\017InstantNewsPack\022-\n\010newsLi" +
      "st\030\001 \003(\0132\033.PB.instantnews.InstantNews*.\n" +
      "\017InstantNewsType\022\n\n\006NORMAL\020\001\022\017\n\013EXCEPTIO" +
      "NAL\020\002B\022B\020InstantNewsTypes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PB_instantnews_InstantNews_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PB_instantnews_InstantNews_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PB_instantnews_InstantNews_descriptor,
        new java.lang.String[] { "Date", "Time", "Title", "Contents", "Type", "Id", });
    internal_static_PB_instantnews_InstantNewsPack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PB_instantnews_InstantNewsPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PB_instantnews_InstantNewsPack_descriptor,
        new java.lang.String[] { "NewsList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
